"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
name = "joerdav"
email = "joe.davidson.21111@gmail.com"

[ui]
editor = "nvim"
default-command = "log"

[signing]
behavior = "own"
backend = "gpg"
key = "25649B006C9E2723C8633960B8343820E7426131"

[aliases]
# tug: bring nearest bookmark up to recent commit
tug = ["bookmark", "move", "--from", "closest_bookmark(@-)", "--to", "@-"]

[revset-aliases]
"closest_bookmark(to)" = "heads(::to & bookmarks())"

# From mitchellh.
[template-aliases]
"format_timestamp(timestamp)" = "timestamp.ago()"
